### ISSUE TITLE
[Bug]: Direct load API occasionally has an error: direct load in ob version 0.0.0.0 is not supported, minimum version required is 4.2.1.7

### ISSUE THREAD

**Issue by yuanoOo** [oceanbase/obkv-table-client-java#230]
### Describe the bug

Direct load API occasionally throws an exception: direct load in ob version 0.0.0.0 is not supported, minimum version required is 4.2.1.7

Executed multiple times, most of the time it can be executed successfully, occasionally the above exception is thrown.

```
Caused by: java.lang.RuntimeException: Fail to obtain direct-load connection.
	at com.oceanbase.spark.directload.DirectLoaderBuilder.build(DirectLoaderBuilder.java:180)
	at com.oceanbase.spark.directload.DirectLoadUtils.buildDirectLoaderFromSetting(DirectLoadUtils.java:46)
	... 13 more
Caused by: com.alipay.oceanbase.rpc.direct_load.exception.ObDirectLoadNotSupportedException: direct load in ob version 0.0.0.0 is not supported, minimum version required is 4.2.1.7
	at com.alipay.oceanbase.rpc.direct_load.protocol.ObDirectLoadProtocolFactory.getProtocol(ObDirectLoadProtocolFactory.java:81)
	at com.alipay.oceanbase.rpc.direct_load.ObDirectLoadConnection.initProtocol(ObDirectLoadConnection.java:188)
	at com.alipay.oceanbase.rpc.direct_load.ObDirectLoadConnection.init(ObDirectLoadConnection.java:87)
	at com.alipay.oceanbase.rpc.direct_load.ObDirectLoadConnectionFactory.buildConnection(ObDirectLoadConnectionFactory.java:44)
	at com.alipay.oceanbase.rpc.direct_load.ObDirectLoadConnection$Builder.build(ObDirectLoadConnection.java:318)
	at com.oceanbase.spark.directload.DirectLoaderBuilder.buildConnection(DirectLoaderBuilder.java:191)
	at com.oceanbase.spark.directload.DirectLoaderBuilder.build(DirectLoaderBuilder.java:163)
	... 14 more

```

### Environment

1.2.14-SNAPSHOT

### Fast reproduce steps

Try calling direct load API multiple times. The above error will appear.

**Comment by whhe** [comment]
https://github.com/oceanbase/spark-connector-oceanbase/actions/runs/11814786983/job/32914558988?pr=5

**Comment by whhe** [comment]
https://github.com/oceanbase/spark-connector-oceanbase/actions/runs/11927804738/job/33243774763
